### ISSUE TITLE
error feedback

### ISSUE THREAD

**Issue by bertvannuffelen** [Informatievlaanderen/OSLO-EA-to-RDF#12]
The following error is thrown when no "definition-nl" tag is present (or the value is empty?).

```
Exception in thread "main" java.lang.NullPointerException: null lexical form for literal
    at org.apache.jena.graph.NodeFactory.createLiteral(NodeFactory.java:133)
    at org.apache.jena.rdf.model.ResourceFactory$Impl.createLangLiteral(ResourceFactory.java:307)
    at org.apache.jena.rdf.model.ResourceFactory.createLangLiteral(ResourceFactory.java:133)
    at com.github.informatievlaanderen.oslo_ea_to_rdf.convert.TagHelper.getTagDataFor(TagHelper.java:106)
    at com.github.informatievlaanderen.oslo_ea_to_rdf.convert.TSVOutputHandler.handleClass(TSVOutputHandler.java:137)
    at com.github.informatievlaanderen.oslo_ea_to_rdf.convert.Converter.convertElement(Converter.java:444)
    at com.github.informatievlaanderen.oslo_ea_to_rdf.convert.Converter.convertDiagram(Converter.java:108)
    at com.github.informatievlaanderen.oslo_ea_to_rdf.Main.main(Main.java:90)
```

**Comment by bertvannuffelen** [comment]
in the new EA-to-RDF version, this is resolved.
