### ISSUE TITLE
Crash bij verwerking vocabularium wanneer meerdere klassen een property hebben met dezelfde naam.

### ISSUE THREAD

**Issue by mvanbrab** [Informatievlaanderen/OSLO-EA-to-RDF#14]
**Praktisch geval**

OSLO-Generiek had twee extra klassen (Samenwerkingsaanvraag en Project) die ook een property 'identifier' definieerden (voorlopig met nog ontbrekende tags).

**Tool output**

Traceback (most recent call last):
  File "../OSLO-SpecificationGenerator/specgen/generate_vocabulary.py", line 115, in <module>
    process_args()
  File "C:\Users\mavbraba\Nextcloud\1\projects\OSLO2_Ondersteuning\Martin\iv\my-env\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\mavbraba\Nextcloud\1\projects\OSLO2_Ondersteuning\Martin\iv\my-env\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\mavbraba\Nextcloud\1\projects\OSLO2_Ondersteuning\Martin\iv\my-env\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\mavbraba\Nextcloud\1\projects\OSLO2_Ondersteuning\Martin\iv\my-env\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "../OSLO-SpecificationGenerator/specgen/generate_vocabulary.py", line 55, in process_args
    xml_output = voc_to_spec(rdf, schema, schema_folder=schema_folder)
  File "C:\Users\mavbraba\Nextcloud\1\projects\OSLO2_Ondersteuning\Martin\iv\OSLO-SpecificationGenerator\specgen\entry.py", line 211, in voc_to_spec
    return render_template(fp, schema, schema_folder, contributors=contributors)
  File "C:\Users\mavbraba\Nextcloud\1\projects\OSLO2_Ondersteuning\Martin\iv\OSLO-SpecificationGenerator\specgen\entry.py", line 188, in render_template
    xml = template.render(record=read_mcf(mcf),
  File "C:\Users\mavbraba\Nextcloud\1\projects\OSLO2_Ondersteuning\Martin\iv\OSLO-SpecificationGenerator\specgen\entry.py", line 129, in read_mcf
    makelist(mcf)
  File "C:\Users\mavbraba\Nextcloud\1\projects\OSLO2_Ondersteuning\Martin\iv\OSLO-SpecificationGenerator\specgen\entry.py", line 116, in makelist
    c.read_file(fh)
  File "C:\Users\mavbraba\AppData\Local\Programs\Python\Python37-32\lib\configparser.py", line 717, in read_file
    self._read(f, source)
  File "C:\Users\mavbraba\AppData\Local\Programs\Python\Python37-32\lib\configparser.py", line 1065, in _read
    lineno)
configparser.DuplicateSectionError: While reading from 'C:\\Users\\mavbraba\\AppData\\Local\\Temp\\tmpmhkt39rr' [line 106]: section 'property_nl:https://data.vlaanderen.be/ns/generiek#identificator' already exists

**Snippet uit de vermelde temp file**

[property_nl:https://data.vlaanderen.be/ns/generiek#identificator]
label=TODO
domain=https://data.vlaanderen.be/ns/generiek#Samenwerkingsaanvraag
range=http://www.w3.org/ns/adms#Identifier
comment=TODO
definedBy=https://data.vlaanderen.be/ns/generiek

[property_nl:https://data.vlaanderen.be/ns/generiek#identificator]
label=TODO
domain=https://data.vlaanderen.be/ns/generiek#Project
range=http://www.w3.org/ns/adms#Identifier
comment=TODO
definedBy=https://data.vlaanderen.be/ns/generiek

** Input EAP file **

[OSLO²_vocabularium-20180820.zip](https://github.com/Informatievlaanderen/OSLO-EA-to-RDF/files/2302868/OSLO._vocabularium-20180820.zip)

**Comment by mvanbrab** [comment]
Oeps, dit is een bug voor OSLO-SpecificationGenerator, niet voor OSLO-EA-to-RDF. Hier sluiten dus...
